CREATE TABLE IF NOT EXISTS events (
    id SERIAL PRIMARY KEY,
    user_id TEXT NOT NULL,
    funnel_name TEXT NOT NULL,
    step_name TEXT NOT NULL,
    event_type TEXT NOT NULL,
    channel TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS funnels (
    id SERIAL PRIMARY KEY,
    funnel_name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS funnel_steps (
    id SERIAL PRIMARY KEY,
    funnel_id INT NOT NULL REFERENCES funnels(id) ON DELETE CASCADE,
    step_name VARCHAR(100) NOT NULL,
    step_order INT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE (funnel_id, step_order),
    UNIQUE (funnel_id, step_name)
);

-- Seed data
INSERT INTO funnels (funnel_name, description)
VALUES ('bank_account_onboarding', 'Bank onboarding funnel for new users')
ON CONFLICT (funnel_name) DO NOTHING;

INSERT INTO funnel_steps (funnel_id, step_name, step_order)
SELECT id, 'account_creation', 1 FROM funnels WHERE funnel_name = 'bank_account_onboarding'
ON CONFLICT DO NOTHING;

INSERT INTO funnel_steps (funnel_id, step_name, step_order)
SELECT id, 'identity_verification', 2 FROM funnels WHERE funnel_name = 'bank_account_onboarding'
ON CONFLICT DO NOTHING;

INSERT INTO funnel_steps (funnel_id, step_name, step_order)
SELECT id, 'document_upload', 3 FROM funnels WHERE funnel_name = 'bank_account_onboarding'
ON CONFLICT DO NOTHING;

INSERT INTO funnel_steps (funnel_id, step_name, step_order)
SELECT id, 'approval', 4 FROM funnels WHERE funnel_name = 'bank_account_onboarding'
ON CONFLICT DO NOTHING;

INSERT INTO events (user_id, funnel_name, step_name, event_type, channel) VALUES
('user_001', 'bank_account_onboarding', 'account_creation', 'start', 'web'),
('user_001', 'bank_account_onboarding', 'identity_verification', 'step', 'web'),
('user_001', 'bank_account_onboarding', 'document_upload', 'step', 'web'),
('user_001', 'bank_account_onboarding', 'approval', 'complete', 'web'),
('user_002', 'bank_account_onboarding', 'account_creation', 'start', 'mobile'),
('user_002', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile'),
('user_003', 'bank_account_onboarding', 'account_creation', 'start', 'web'),
('user_003', 'bank_account_onboarding', 'identity_verification', 'step', 'web'),
('user_003', 'bank_account_onboarding', 'document_upload', 'step', 'web'),
('user_004', 'bank_account_onboarding', 'account_creation', 'start', 'mobile'),
('user_004', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile'),
('user_004', 'bank_account_onboarding', 'document_upload', 'step', 'mobile'),
('user_004', 'bank_account_onboarding', 'approval', 'complete', 'mobile'),
('user_005', 'bank_account_onboarding', 'account_creation', 'start', 'web'),
('user_006', 'bank_account_onboarding', 'account_creation', 'start', 'mobile'),
('user_006', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile'),
('user_006', 'bank_account_onboarding', 'document_upload', 'step', 'mobile'),
('user_007', 'bank_account_onboarding', 'account_creation', 'start', 'web'),
('user_007', 'bank_account_onboarding', 'identity_verification', 'step', 'web'),
('user_007', 'bank_account_onboarding', 'document_upload', 'step', 'web'),
('user_007', 'bank_account_onboarding', 'approval', 'complete', 'web'),
('user_008', 'bank_account_onboarding', 'account_creation', 'start', 'mobile'),
('user_008', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile'),
('user_009', 'bank_account_onboarding', 'account_creation', 'start', 'web'),
('user_009', 'bank_account_onboarding', 'identity_verification', 'step', 'web'),
('user_009', 'bank_account_onboarding', 'document_upload', 'step', 'web'),
('user_009', 'bank_account_onboarding', 'approval', 'complete', 'web'),
('user_010', 'bank_account_onboarding', 'account_creation', 'start', 'web'),
('user_010', 'bank_account_onboarding', 'identity_verification', 'step', 'web'),
('user_010', 'bank_account_onboarding', 'document_upload', 'step', 'web'),
('user_0010', 'bank_account_onboarding', 'approval', 'complete', 'web');

INSERT INTO events (user_id, funnel_name, step_name, event_type, channel, created_at) VALUES
('user_011', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '10 days'),
('user_011', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '10 days' + INTERVAL '3 minutes'),
('user_011', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '10 days' + INTERVAL '18 minutes'),
('user_011', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '10 days' + INTERVAL '25 minutes'),
('user_012', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '10 days' + INTERVAL '1 hour'),
('user_012', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '10 days' + INTERVAL '1 hour' + INTERVAL '5 minutes'),
('user_013', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '9 days'),
('user_013', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '9 days' + INTERVAL '2 minutes'),
('user_013', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '9 days' + INTERVAL '10 minutes'),
('user_013', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '9 days' + INTERVAL '20 minutes'),
('user_014', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '9 days' + INTERVAL '2 hours'),
('user_014', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '9 days' + INTERVAL '2 hours' + INTERVAL '8 minutes'),
('user_014', 'bank_account_onboarding', 'document_upload', 'step', 'mobile', NOW() - INTERVAL '9 days' + INTERVAL '2 hours' + INTERVAL '45 minutes'),
('user_015', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '8 days'),
('user_016', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '8 days' + INTERVAL '3 hours'),
('user_016', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '8 days' + INTERVAL '3 hours' + INTERVAL '6 minutes'),
('user_016', 'bank_account_onboarding', 'document_upload', 'step', 'mobile', NOW() - INTERVAL '8 days' + INTERVAL '3 hours' + INTERVAL '30 minutes'),
('user_016', 'bank_account_onboarding', 'approval', 'complete', 'mobile', NOW() - INTERVAL '8 days' + INTERVAL '3 hours' + INTERVAL '40 minutes'),
('user_017', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '7 days'),
('user_017', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '7 days' + INTERVAL '1 minute'),
('user_017', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '7 days' + INTERVAL '8 minutes'),
('user_017', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '7 days' + INTERVAL '15 minutes'),
('user_018', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '7 days' + INTERVAL '1 hour'),
('user_018', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '7 days' + INTERVAL '1 hour' + INTERVAL '12 minutes'),
('user_019', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '6 days'),
('user_019', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '6 days' + INTERVAL '4 minutes'),
('user_019', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '6 days' + INTERVAL '22 minutes'),
('user_020', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '6 days' + INTERVAL '2 hours'),
('user_020', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '6 days' + INTERVAL '2 hours' + INTERVAL '5 minutes'),
('user_020', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '6 days' + INTERVAL '2 hours' + INTERVAL '20 minutes'),
('user_020', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '6 days' + INTERVAL '2 hours' + INTERVAL '30 minutes'),
('user_021', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '5 days'),
('user_022', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '5 days' + INTERVAL '1 hour'),
('user_022', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '5 days' + INTERVAL '1 hour' + INTERVAL '20 minutes'),
('user_022', 'bank_account_onboarding', 'document_upload', 'step', 'mobile', NOW() - INTERVAL '5 days' + INTERVAL '1 hour' + INTERVAL '55 minutes'),
('user_022', 'bank_account_onboarding', 'approval', 'complete', 'mobile', NOW() - INTERVAL '5 days' + INTERVAL '2 hours' + INTERVAL '10 minutes'),
('user_023', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '4 days'),
('user_023', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '4 days' + INTERVAL '2 minutes'),
('user_023', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '4 days' + INTERVAL '12 minutes'),
('user_023', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '4 days' + INTERVAL '22 minutes'),
('user_024', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '4 days' + INTERVAL '3 hours'),
('user_024', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '4 days' + INTERVAL '3 hours' + INTERVAL '10 minutes'),
('user_024', 'bank_account_onboarding', 'document_upload', 'step', 'mobile', NOW() - INTERVAL '4 days' + INTERVAL '3 hours' + INTERVAL '60 minutes'),
('user_025', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '3 days'),
('user_025', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '3 days' + INTERVAL '3 minutes'),
('user_025', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '3 days' + INTERVAL '15 minutes'),
('user_025', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '3 days' + INTERVAL '28 minutes'),
('user_026', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '3 days' + INTERVAL '2 hours'),
('user_026', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '3 days' + INTERVAL '2 hours' + INTERVAL '15 minutes'),
('user_027', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '2 days'),
('user_027', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '2 days' + INTERVAL '4 minutes'),
('user_027', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '2 days' + INTERVAL '18 minutes'),
('user_028', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '2 days' + INTERVAL '1 hour'),
('user_028', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '2 days' + INTERVAL '1 hour' + INTERVAL '2 minutes'),
('user_028', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '2 days' + INTERVAL '1 hour' + INTERVAL '9 minutes'),
('user_028', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '2 days' + INTERVAL '1 hour' + INTERVAL '17 minutes'),
('user_029', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '1 day'),
('user_029', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '1 day' + INTERVAL '7 minutes'),
('user_029', 'bank_account_onboarding', 'document_upload', 'step', 'mobile', NOW() - INTERVAL '1 day' + INTERVAL '35 minutes'),
('user_029', 'bank_account_onboarding', 'approval', 'complete', 'mobile', NOW() - INTERVAL '1 day' + INTERVAL '50 minutes'),
('user_030', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '2 hours'),
('user_031', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '15 days'),
('user_031', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '15 days' + INTERVAL '4 minutes'),
('user_031', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '15 days' + INTERVAL '14 minutes'),
('user_031', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '15 days' + INTERVAL '22 minutes'),
('user_032', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '15 days' + INTERVAL '2 hours'),
('user_032', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '15 days' + INTERVAL '2 hours' + INTERVAL '9 minutes'),
('user_033', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '14 days'),
('user_033', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '14 days' + INTERVAL '3 minutes'),
('user_033', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '14 days' + INTERVAL '11 minutes'),
('user_033', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '14 days' + INTERVAL '19 minutes'),
('user_034', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '14 days' + INTERVAL '1 hour'),
('user_034', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '14 days' + INTERVAL '1 hour' + INTERVAL '8 minutes'),
('user_034', 'bank_account_onboarding', 'document_upload', 'step', 'mobile', NOW() - INTERVAL '14 days' + INTERVAL '1 hour' + INTERVAL '40 minutes'),
('user_034', 'bank_account_onboarding', 'approval', 'complete', 'mobile', NOW() - INTERVAL '14 days' + INTERVAL '1 hour' + INTERVAL '55 minutes'),
('user_035', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '13 days'),
('user_035', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '13 days' + INTERVAL '5 minutes'),
('user_035', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '13 days' + INTERVAL '25 minutes'),
('user_036', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '13 days' + INTERVAL '3 hours'),
('user_037', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '12 days'),
('user_037', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '12 days' + INTERVAL '2 minutes'),
('user_037', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '12 days' + INTERVAL '10 minutes'),
('user_037', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '12 days' + INTERVAL '18 minutes'),
('user_038', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '12 days' + INTERVAL '2 hours'),
('user_038', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '12 days' + INTERVAL '2 hours' + INTERVAL '11 minutes'),
('user_038', 'bank_account_onboarding', 'document_upload', 'step', 'mobile', NOW() - INTERVAL '12 days' + INTERVAL '2 hours' + INTERVAL '50 minutes'),
('user_039', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '11 days'),
('user_039', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '11 days' + INTERVAL '3 minutes'),
('user_039', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '11 days' + INTERVAL '13 minutes'),
('user_039', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '11 days' + INTERVAL '21 minutes'),
('user_040', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '11 days' + INTERVAL '1 hour'),
('user_040', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '11 days' + INTERVAL '1 hour' + INTERVAL '7 minutes'),
('user_040', 'bank_account_onboarding', 'document_upload', 'step', 'mobile', NOW() - INTERVAL '11 days' + INTERVAL '1 hour' + INTERVAL '35 minutes'),
('user_040', 'bank_account_onboarding', 'approval', 'complete', 'mobile', NOW() - INTERVAL '11 days' + INTERVAL '1 hour' + INTERVAL '48 minutes'),
('user_041', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '10 days' + INTERVAL '5 hours'),
('user_041', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '10 days' + INTERVAL '5 hours' + INTERVAL '6 minutes'),
('user_042', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '10 days' + INTERVAL '6 hours'),
('user_043', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '9 days' + INTERVAL '3 hours'),
('user_043', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '9 days' + INTERVAL '3 hours' + INTERVAL '1 minute'),
('user_043', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '9 days' + INTERVAL '3 hours' + INTERVAL '7 minutes'),
('user_043', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '9 days' + INTERVAL '3 hours' + INTERVAL '13 minutes'),
('user_044', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '8 days' + INTERVAL '4 hours'),
('user_044', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '8 days' + INTERVAL '4 hours' + INTERVAL '10 minutes'),
('user_044', 'bank_account_onboarding', 'document_upload', 'step', 'mobile', NOW() - INTERVAL '8 days' + INTERVAL '4 hours' + INTERVAL '45 minutes'),
('user_044', 'bank_account_onboarding', 'approval', 'complete', 'mobile', NOW() - INTERVAL '8 days' + INTERVAL '4 hours' + INTERVAL '58 minutes'),
('user_045', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '7 days' + INTERVAL '2 hours'),
('user_045', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '7 days' + INTERVAL '2 hours' + INTERVAL '4 minutes'),
('user_045', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '7 days' + INTERVAL '2 hours' + INTERVAL '16 minutes'),
('user_046', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '6 days' + INTERVAL '1 hour'),
('user_046', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '6 days' + INTERVAL '1 hour' + INTERVAL '14 minutes'),
('user_047', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '5 days' + INTERVAL '3 hours'),
('user_047', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '5 days' + INTERVAL '3 hours' + INTERVAL '2 minutes'),
('user_047', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '5 days' + INTERVAL '3 hours' + INTERVAL '11 minutes'),
('user_047', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '5 days' + INTERVAL '3 hours' + INTERVAL '20 minutes'),
('user_048', 'bank_account_onboarding', 'account_creation', 'start', 'mobile', NOW() - INTERVAL '4 days' + INTERVAL '2 hours'),
('user_048', 'bank_account_onboarding', 'identity_verification', 'step', 'mobile', NOW() - INTERVAL '4 days' + INTERVAL '2 hours' + INTERVAL '18 minutes'),
('user_048', 'bank_account_onboarding', 'document_upload', 'step', 'mobile', NOW() - INTERVAL '4 days' + INTERVAL '2 hours' + INTERVAL '58 minutes'),
('user_048', 'bank_account_onboarding', 'approval', 'complete', 'mobile', NOW() - INTERVAL '4 days' + INTERVAL '3 hours' + INTERVAL '15 minutes'),
('user_049', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '3 days' + INTERVAL '4 hours'),
('user_049', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '3 days' + INTERVAL '4 hours' + INTERVAL '5 minutes'),
('user_049', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '3 days' + INTERVAL '4 hours' + INTERVAL '20 minutes'),
('user_050', 'bank_account_onboarding', 'account_creation', 'start', 'web', NOW() - INTERVAL '2 days' + INTERVAL '3 hours'),
('user_050', 'bank_account_onboarding', 'identity_verification', 'step', 'web', NOW() - INTERVAL '2 days' + INTERVAL '3 hours' + INTERVAL '3 minutes'),
('user_050', 'bank_account_onboarding', 'document_upload', 'step', 'web', NOW() - INTERVAL '2 days' + INTERVAL '3 hours' + INTERVAL '12 minutes'),
('user_050', 'bank_account_onboarding', 'approval', 'complete', 'web', NOW() - INTERVAL '2 days' + INTERVAL '3 hours' + INTERVAL '23 minutes');
